version: 2.1

orbs:
  silta: silta/silta@0.1.130

executors:
  cicd81:
    docker:
      - image: wunderio/silta-cicd:circleci-php8.1-node16-composer2

workflows:
  commit:
    jobs:
      - silta/drupal-validate:
          name: Validate Drupal code
          executor: cicd81
          post-validation:
            - run: echo "You can add additional validation here!"

      - silta/analyze:
          name: Analyze code
          context: analyze
          sources: web

      - silta/drupal-build-deploy: &build-deploy
          name: Build and deploy Drupal
          executor: cicd81
          codebase-build:
            - silta/drupal-composer-install
            - silta/npm-install-build
          context: silta_dev
          filters:
            branches:
              ignore:
                - production
                - /dependabot\/.*/

      - silta/drupal-build-deploy:
          # Extend the build-deploy configuration for the production environment.
          <<: *build-deploy
          name: Build and deploy Drupal to production
          silta_config: silta/silta.yml,silta/silta-prod.yml
          context: silta_finland
          filters:
            branches:
              only: production

      - silta/drupal-build-deploy:
          <<: *build-deploy
          name: Build and deploy Dependabot
          context: silta_dev
          skip-deployment: true
          filters:
            branches:
              only: /dependabot\/.*/

      - silta/frontend-build-deploy: &frontend-build-deploy
          name: Build and deploy frontend
          context: silta_dev
          silta_config: silta/silta.yml
          codebase-build:
            - silta/npm-install-build
          filters:
            branches:
              ignore:
                - production
                - /dependabot\/.*/

      - silta/frontend-build-deploy:
          # Extend the build-deploy configuration for the production environment.
          <<: *frontend-build-deploy
          name: Build and deploy frontend to production
          context: silta_finland
          silta_config: silta/silta.yml,silta/silta-prod.yml
          filters:
            branches:
              only: production

      - silta/frontend-build-deploy:
          <<: *frontend-build-deploy
          name: Build Dependabot frontend
          context: silta_dev
          skip-deployment: true
          filters:
            branches:
              only: /dependabot\/.*/

